[package]
name = "deimos"
version = "0.1.0"
edition = "2021"

[dependencies]
luna-lib = "0.4.1"
sdl2 = { version = "0.36.0" }

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
strip = true